pull_request_rules:
  - name: Automatic merge when approvals
    conditions:
      - author!=javiyt
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
  - name: Automatic merge on author
    conditions:
      - author=javiyt
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
      comment:
        message: This pull request is now in conflicts. Could you fix it @{{author}}? 🙏
